### ISSUE TITLE
Reimplement APIError Exception class

### ISSUE THREAD

**Issue by bbck** [BinaryMuse/battlenet#3]
Glad to see this gem is getting some love again. The 1.0.0 release removed the APIError exception and now just has a string. This makes it more difficult to see why an exception was thrown. If possible I would like to request this be revered back to pre 1.0.0.

**Comment by BinaryMuse** [comment]
Thanks for the kind words, bbck.

Version 1.2 will have exceptions for all known error messages returned from the API endpoint as well as for undocumented/unknown errors.
